export const currencies = [
  { code: "brl", name: "Brazilian Real", flag: "https://flagcdn.com/br.svg" },
  { code: "usd", name: "United States Dollar", flag: "https://flagcdn.com/us.svg" },
  { code: "eur", name: "Euro", flag: "https://flagcdn.com/eu.svg" },
  { code: "gbp", name: "British Pound Sterling", flag: "https://flagcdn.com/gb.svg" },
  { code: "jpy", name: "Japanese Yen", flag: "https://flagcdn.com/jp.svg" },
  { code: "aud", name: "Australian Dollar", flag: "https://flagcdn.com/au.svg" },
  { code: "cad", name: "Canadian Dollar", flag: "https://flagcdn.com/ca.svg" },
  { code: "chf", name: "Swiss Franc", flag: "https://flagcdn.com/ch.svg" },
  { code: "cny", name: "Chinese Yuan", flag: "https://flagcdn.com/cn.svg" },
  { code: "inr", name: "Indian Rupee", flag: "https://flagcdn.com/in.svg" },
  { code: "rub", name: "Russian Ruble", flag: "https://flagcdn.com/ru.svg" },
  { code: "zar", name: "South African Rand", flag: "https://flagcdn.com/za.svg" },
  { code: "mxn", name: "Mexican Peso", flag: "https://flagcdn.com/mx.svg" },
  { code: "krw", name: "South Korean Won", flag: "https://flagcdn.com/kr.svg" },
  { code: "sgd", name: "Singapore Dollar", flag: "https://flagcdn.com/sg.svg" },
  { code: "hkd", name: "Hong Kong Dollar", flag: "https://flagcdn.com/hk.svg" },
  { code: "nzd", name: "New Zealand Dollar", flag: "https://flagcdn.com/nz.svg" },
  { code: "sek", name: "Swedish Krona", flag: "https://flagcdn.com/se.svg" },
  { code: "nok", name: "Norwegian Krone", flag: "https://flagcdn.com/no.svg" },
  { code: "dkk", name: "Danish Krone", flag: "https://flagcdn.com/dk.svg" },
  { code: "pln", name: "Polish Zloty", flag: "https://flagcdn.com/pl.svg" },
  { code: "try", name: "Turkish Lira", flag: "https://flagcdn.com/tr.svg" },
  { code: "thb", name: "Thai Baht", flag: "https://flagcdn.com/th.svg" },
  { code: "idr", name: "Indonesian Rupiah", flag: "https://flagcdn.com/id.svg" },
  { code: "myr", name: "Malaysian Ringgit", flag: "https://flagcdn.com/my.svg" },
  { code: "php", name: "Philippine Peso", flag: "https://flagcdn.com/ph.svg" },
  { code: "czk", name: "Czech Koruna", flag: "https://flagcdn.com/cz.svg" },
  { code: "huf", name: "Hungarian Forint", flag: "https://flagcdn.com/hu.svg" },
  { code: "ils", name: "Israeli New Shekel", flag: "https://flagcdn.com/il.svg" },
  { code: "sar", name: "Saudi Riyal", flag: "https://flagcdn.com/sa.svg" },
  { code: "aed", name: "United Arab Emirates Dirham", flag: "https://flagcdn.com/ae.svg" },
];