export const currencies = [
  { code: "BRL", name: "Brazilian Real", flag: "https://flagcdn.com/br.svg" },
  { code: "USD", name: "United States Dollar", flag: "https://flagcdn.com/us.svg" },
  { code: "EUR", name: "Euro", flag: "https://flagcdn.com/eu.svg" },
  { code: "GBP", name: "British Pound Sterling", flag: "https://flagcdn.com/gb.svg" },
  { code: "JPY", name: "Japanese Yen", flag: "https://flagcdn.com/jp.svg" },
  { code: "AUD", name: "Australian Dollar", flag: "https://flagcdn.com/au.svg" },
  { code: "CAD", name: "Canadian Dollar", flag: "https://flagcdn.com/ca.svg" },
  { code: "CHF", name: "Swiss Franc", flag: "https://flagcdn.com/ch.svg" },
  { code: "CNY", name: "Chinese Yuan", flag: "https://flagcdn.com/cn.svg" },
  { code: "INR", name: "Indian Rupee", flag: "https://flagcdn.com/in.svg" },
  { code: "RUB", name: "Russian Ruble", flag: "https://flagcdn.com/ru.svg" },
  { code: "ZAR", name: "South African Rand", flag: "https://flagcdn.com/za.svg" },
  { code: "MXN", name: "Mexican Peso", flag: "https://flagcdn.com/mx.svg" },
  { code: "KRW", name: "South Korean Won", flag: "https://flagcdn.com/kr.svg" },
  { code: "SGD", name: "Singapore Dollar", flag: "https://flagcdn.com/sg.svg" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "https://flagcdn.com/hk.svg" },
  { code: "NZD", name: "New Zealand Dollar", flag: "https://flagcdn.com/nz.svg" },
  { code: "SEK", name: "Swedish Krona", flag: "https://flagcdn.com/se.svg" },
  { code: "NOK", name: "Norwegian Krone", flag: "https://flagcdn.com/no.svg" },
  { code: "DKK", name: "Danish Krone", flag: "https://flagcdn.com/dk.svg" },
  { code: "PLN", name: "Polish Zloty", flag: "https://flagcdn.com/pl.svg" },
  { code: "TRY", name: "Turkish Lira", flag: "https://flagcdn.com/tr.svg" },
  { code: "THB", name: "Thai Baht", flag: "https://flagcdn.com/th.svg" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "https://flagcdn.com/id.svg" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "https://flagcdn.com/my.svg" },
  { code: "PHP", name: "Philippine Peso", flag: "https://flagcdn.com/ph.svg" },
  { code: "CZK", name: "Czech Koruna", flag: "https://flagcdn.com/cz.svg" },
  { code: "HUF", name: "Hungarian Forint", flag: "https://flagcdn.com/hu.svg" },
  { code: "ILS", name: "Israeli New Shekel", flag: "https://flagcdn.com/il.svg" },
  { code: "SAR", name: "Saudi Riyal", flag: "https://flagcdn.com/sa.svg" },
  { code: "AED", name: "United Arab Emirates Dirham", flag: "https://flagcdn.com/ae.svg" },
];