export const currencies = [
  { code: "brl", name: "Brazilian Real", flag: "br" },
  { code: "usd", name: "United States Dollar", flag: "us" },
  { code: "eur", name: "Euro", flag: "eu" },
  { code: "gbp", name: "British Pound Sterling", flag: "gb" },
  { code: "jpy", name: "Japanese Yen", flag: "jp" },
  { code: "aud", name: "Australian Dollar", flag: "au" },
  { code: "cad", name: "Canadian Dollar", flag: "ca" },
  { code: "chf", name: "Swiss Franc", flag: "ch" },
  { code: "cny", name: "Chinese Yuan", flag: "cn" },
  { code: "inr", name: "Indian Rupee", flag: "in" },
  { code: "rub", name: "Russian Ruble", flag: "ru" },
  { code: "zar", name: "South African Rand", flag: "za" },
  { code: "mxn", name: "Mexican Peso", flag: "mx" },
  { code: "krw", name: "South Korean Won", flag: "kr" },
  { code: "sgd", name: "Singapore Dollar", flag: "sg" },
  { code: "hkd", name: "Hong Kong Dollar", flag: "hk" },
  { code: "nzd", name: "New Zealand Dollar", flag: "nz" },
  { code: "sek", name: "Swedish Krona", flag: "se" },
  { code: "nok", name: "Norwegian Krone", flag: "no" },
  { code: "dkk", name: "Danish Krone", flag: "dk" },
  { code: "pln", name: "Polish Zloty", flag: "pl" },
  { code: "try", name: "Turkish Lira", flag: "tr" },
  { code: "thb", name: "Thai Baht", flag: "th" },
  { code: "idr", name: "Indonesian Rupiah", flag: "id" },
  { code: "myr", name: "Malaysian Ringgit", flag: "my" },
  { code: "php", name: "Philippine Peso", flag: "ph" },
  { code: "czk", name: "Czech Koruna", flag: "cz" },
  { code: "huf", name: "Hungarian Forint", flag: "hu" },
  { code: "ils", name: "Israeli New Shekel", flag: "il" },
  { code: "sar", name: "Saudi Riyal", flag: "sa" },
  { code: "aed", name: "United Arab Emirates Dirham", flag: "ae" },
];